services:
  - type: web
    name: scandiweb-backend
    runtime: docker
    region: frankfurt
    rootDir: backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: scandiweb-mysql
          property: host
      - key: DB_PORT
        fromDatabase:
          name: scandiweb-mysql
          property: port
      - key: DB_NAME
        fromDatabase:
          name: scandiweb-mysql
          property: database
      - key: DB_USER
        fromDatabase:
          name: scandiweb-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: scandiweb-mysql
          property: password
      - key: DB_CHARSET
        value: utf8mb4

databases:
  - name: scandiweb-mysql
    databaseName: scandiweb_ecommerce
    user: scandiweb
    region: frankfurt