services:
  - type: web
    name: scandiweb-backend
    runtime: docker
    region: frankfurt
    rootDir: backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: scandiweb-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: scandiweb-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: scandiweb-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: scandiweb-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: scandiweb-db
          property: password

databases:
  - name: scandiweb-db
    databaseName: scandiweb_ecommerce
    user: scandiweb_user
    region: frankfurt